services:
  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:4173"
    depends_on:
      - pocketbase

  pocketbase:
    build: 
      context: ./pocketbase
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
