services:
  # backend:
  #   build: 
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - mongo

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:5173"
    depends_on:
      - pocketbase

  pocketbase:
    build: 
      context: ./pocketbase
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
